spring:
  profiles:
    active: dev
  application:
    name: find-phone-manager
server:
  port: 8989


#mp-plus的配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0