spring:
  application:
    name: find-phone-gateway
  cloud:
    gateway:
      routes:
        - id: find-phone-manager
          uri: http://localhost:8989
          predicates:
            - Path=/api/manager/**
          filters:
            - RewritePath=/api/manager/(?<segment>/?.*),/manager/$\{segment}
        - id: find-phone-manager-swagger
          uri: http://localhost:8989
          predicates:
            - Path=/**
  profiles:
    active: dev
#            filters:
#              - RewritePath=/(?<segment>/?.*),/$\{segment}
server:
  port: 7789

#mp-plus的配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
